### ISSUE TITLE
Version for macOS <10.15

### ISSUE THREAD

**Issue by mstgrv** [confirmedcode/Lockdown-Mac#1]
Excited to try Lockdown on Mac, but the Mac App Store says it requires 10.15 and I'm running 10.14. Any chance you would be able to provide a version for pre-Catalina versions of macOS?

**Comment by vinbrule** [comment]
I am on the same boat also, cannot install to <10.15

**Comment by hijohnnylin** [comment]
Hey - thanks for the feedback. We use SwiftUI, which requires macOS 10.15+. Some NetworkExtensions/Kernel APIs are also being deprecated or changed pretty quickly on macOS by Apple, so it's more future-proof for us to rely on the new ones rather than complicate things by trying to make both old and new APIs work.

Sources:
https://developer.apple.com/documentation/swiftui
https://www.zdnet.com/article/apple-deprecating-macos-kernel-extensions-kexts-is-a-great-win-for-security/
