### ISSUE TITLE
Doesn't work with Mullvad VPN

### ISSUE THREAD

**Issue by sahilc0** [confirmedcode/Lockdown-Mac#11]
Lockdown doesn't seem to work with Mullvad. How can we get Lockdown to play better with other VPNs?

**Comment by orthodoX** [comment]
@sahilc0 I don't think Lockdown is designed to work with other VPNs. Since it's directly interacting with your IP address not being publicly exposed. That prevent other VPN tools to address you. I always turn it off if I need to connect a VPN service and I think this is a normal and expected behaviour.

**Comment by sahilc0** [comment]
Dumb question though - lockdown itself has a built in VPN. That supposedly works in conjunction with the adblocking. 

Why would that be any different?

**Comment by orthodoX** [comment]
@sahilc0 You might need a VPN only to hide yourself online. Many people, including myself have a need to connect to a specific VPN, in order to access their work networks, so when I need to do that I must have my IP not masked by Lockdown, and disabling it is a reasonable thing to do.

**Comment by sahilc0** [comment]
Sure, I’m not suggesting Lockdown masks the VPN - I’m saying Lockdown should play better with other VPNs so you can both run the firewall and your VPN at the same time
